<?php

namespace Proxies\__CG__\MRF\MenuBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Menu extends \MRF\MenuBundle\Entity\Menu implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'MRF\\MenuBundle\\Entity\\Menu' . "\0" . 'id', '' . "\0" . 'MRF\\MenuBundle\\Entity\\Menu' . "\0" . 'nombre', '' . "\0" . 'MRF\\MenuBundle\\Entity\\Menu' . "\0" . 'ruta', '' . "\0" . 'MRF\\MenuBundle\\Entity\\Menu' . "\0" . 'listar', '' . "\0" . 'MRF\\MenuBundle\\Entity\\Menu' . "\0" . 'agregar', '' . "\0" . 'MRF\\MenuBundle\\Entity\\Menu' . "\0" . 'editar', '' . "\0" . 'MRF\\MenuBundle\\Entity\\Menu' . "\0" . 'eliminar');
        }

        return array('__isInitialized__', '' . "\0" . 'MRF\\MenuBundle\\Entity\\Menu' . "\0" . 'id', '' . "\0" . 'MRF\\MenuBundle\\Entity\\Menu' . "\0" . 'nombre', '' . "\0" . 'MRF\\MenuBundle\\Entity\\Menu' . "\0" . 'ruta', '' . "\0" . 'MRF\\MenuBundle\\Entity\\Menu' . "\0" . 'listar', '' . "\0" . 'MRF\\MenuBundle\\Entity\\Menu' . "\0" . 'agregar', '' . "\0" . 'MRF\\MenuBundle\\Entity\\Menu' . "\0" . 'editar', '' . "\0" . 'MRF\\MenuBundle\\Entity\\Menu' . "\0" . 'eliminar');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Menu $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setRuta($ruta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRuta', array($ruta));

        return parent::setRuta($ruta);
    }

    /**
     * {@inheritDoc}
     */
    public function getRuta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRuta', array());

        return parent::getRuta();
    }

    /**
     * {@inheritDoc}
     */
    public function setListar($listar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setListar', array($listar));

        return parent::setListar($listar);
    }

    /**
     * {@inheritDoc}
     */
    public function getListar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListar', array());

        return parent::getListar();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgregar($agregar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgregar', array($agregar));

        return parent::setAgregar($agregar);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgregar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgregar', array());

        return parent::getAgregar();
    }

    /**
     * {@inheritDoc}
     */
    public function setEditar($editar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEditar', array($editar));

        return parent::setEditar($editar);
    }

    /**
     * {@inheritDoc}
     */
    public function getEditar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEditar', array());

        return parent::getEditar();
    }

    /**
     * {@inheritDoc}
     */
    public function setEliminar($eliminar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEliminar', array($eliminar));

        return parent::setEliminar($eliminar);
    }

    /**
     * {@inheritDoc}
     */
    public function getEliminar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEliminar', array());

        return parent::getEliminar();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
