<?php

namespace MRF\MenuRolBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRolRepository extends EntityRepository
{
}
